
% reshape, resize and redefine input to predictable formats
function [popsize,...          
          confcn,...
          constrained,...
          which_ones,...
          options] = reformat_input(dimensions, varargin)


   
    

end  
